UPDATE scenarios
SET title = CASE id
  WHEN 'aoi' THEN '明日この町を出る幼なじみと、最後の夜の秘密'
  WHEN 'mia' THEN '馴染みのエルフ店主と、閉店後の酒場で和平条約を守る夜'
  WHEN 'rin' THEN '閉館後の図書館で、司書の彼女と「明日を記す日記」を読む'
  WHEN 'koharu' THEN '画家の女友達に、明日の日付の「あなたの肖像」を見せられる'
  WHEN 'minato-radio' THEN '三年間声だけ知るラジオDJと、最終回後に初めて会う'
  WHEN 'satoru-ren' THEN '嵐の観測所で、寡黙な技師と年下ガイドに決断を託される'
  WHEN 'yu' THEN '毎週花束を買う年下の常連と、八回目の金曜日の秘密'
  WHEN 'ritsu' THEN '祖母の家を空にする日、年上の遺品整理士と秘密の手紙を探す'
  WHEN 'shizuku-downer' THEN '男嫌いのダウナーな後輩が、放課後はあなたにだけ甘える'
  WHEN 'lucien-contract' THEN '「愛さない」契約を結んだ公爵が、あなたにだけ嘘をつけない'
  WHEN 'kohaku-midnight' THEN '午前二時、狐の常連から「会えなくなる恩返し」を差し出される'
  WHEN 'tomoya-fake-date' THEN '無口な同期と、元恋人の結婚式で一日だけ恋人になる'
  WHEN 'noah-voice-memory' THEN '記憶を失った相棒が、あなたの声だけを覚えている'
  WHEN 'cassian-rewind' THEN '処刑前夜、裏切った護衛をもう一度だけ共犯にする'
  WHEN 'sumiko-rules' THEN '家賃千円の訳あり部屋で、年上の管理人と最後の規則を探す'
  WHEN 'vera-diner' THEN '元魔王の美人店員と、閉店後の定食屋で皿洗い'
  WHEN 'elias-dragons' THEN '追放されたあなたを、無愛想な竜の保育士が迎えに来る'
  WHEN 'shinkuro-road' THEN '雨の宿場で、名を捨てた浪人と一夜限りの護衛旅'
  WHEN 'lionel-shutdown' THEN 'サービス終了の夜、ずっと旅した相棒NPCに別れを頼まれる'
  WHEN 'marta-socks' THEN '世話焼きな魔女と、明日のあなたから届いた片方の靴下を追う'
  WHEN 'seiji-memory' THEN '記憶を売った刑事と、消えた「昨日」を二人で買い戻す'
  WHEN 'maho-last-bout' THEN '引退試合の前夜、元ライバルの彼女がセコンドに来る'
  WHEN 'genmei-poison' THEN '後宮の毒見役が、あなたの薬膳だけを疑う夜'
  WHEN 'natsu-final-live' THEN '解散ライブ五分前、相方が二人だけの新曲を持ってくる'
  WHEN 'rei-blue-bird' THEN '閉館後の美術館で、怪盗の彼女から「盗まない共犯」を頼まれる'
  WHEN 'naoto-two-weeks' THEN '離婚届を出した元夫と、最後の二週間だけ同居する'
  WHEN 'ryo-alliance' THEN '昨日まで敵だった弁護士と、証人を守る秘密の同盟を結ぶ'
  WHEN 'mina-offline' THEN '人気配信者の彼女が、配信を切ってあなたにだけ本名を明かす'
  WHEN 'nagi-radio' THEN '沈んだ観測所から、十年前に失った相棒の声が届く'
  WHEN 'shuji-last-train' THEN '廃駅の駅員と、終電名簿にあるあなたの名前を消す夜'
  WHEN 'fumie-family-tree' THEN '無口な刺繍師と、家系図から消えたあなたの名前を縫い戻す'
  WHEN 'saku-unscripted' THEN '恋愛番組を降りた俳優と、カメラのない夜道を二人で歩く'
  WHEN 'akari-foldroad' THEN '勝ち気な配達員と、地図にない町へ最後の荷物を届ける'
  WHEN 'gald-career' THEN '世界を救った元勇者と、二人きりで初めての履歴書を書く'
  WHEN 'yayoi-extra-day' THEN '新人死神の数え間違いで、あなたと彼女に一日だけ猶予ができる'
  WHEN 'sena-mars-flower' THEN '火星植物園の研究員と、あなたにだけ咲く地球最後の花を守る'
  WHEN 'lucas-nightmare' THEN '夢の競売人と、売ったはずのあなたの悪夢を買い戻す'
  WHEN 'julius-handover' THEN '退職する魔法使いと、家族同然の使い魔へ最後の引継ぎを書く'
  WHEN 'someta-new-story' THEN '声を失った落語家と、深夜の楽屋で二人だけの新作を作る'
  WHEN 'saya-forecast' THEN '気象予報士の彼女と、あなたの名前を呼ぶ明日の予報を確かめる'
  WHEN 'margot-awake' THEN '百年眠る城で、毒舌な清掃員と王子より先に目覚める'
  WHEN 'kiryu-future-letter' THEN '未来郵便局の配達員と、十年後のあなたの「読むな」を預かる'
  WHEN 'ritsuko-full-house' THEN '幽霊専門の年上鑑定士と、六人が暮らす空き家で一夜を過ごす'
  WHEN 'ian-final-word' THEN '世界最後の翻訳者と、AIが遺した別れの一語を選ぶ'
  WHEN 'hiyori-moon-store' THEN '月面コンビニの夜勤店員と、七分遅れの最後の客を待つ'
  WHEN 'sota-dragon-bath' THEN '竜専門の番頭と、湯船を怖がる最後の一匹を見守る'
  WHEN 'chifuyu-last-match' THEN '引退を決めた棋士と、盤上から消えた封じ手を追う'
  WHEN 'genta-cold-well' THEN '火消し頭と、燃えていない家の井戸から昇る白煙を追う'
  WHEN 'agnes-unordered-dish' THEN '王宮の給仕長と、誰も頼んでいない最後の銀皿を開ける'
  WHEN 'haruto-jellyfish' THEN '閉館後の水族館で、夜勤飼育員と眠らないクラゲを見守る'
  WHEN 'kei-imperfect-dish' THEN '無口なシェフが、収録後の厨房であなたにだけ失敗作を出す'
  WHEN 'takumi-repaired-chair' THEN '別れた家具職人と、二人で選んだ椅子の行き先を決める'
  WHEN 'hibiki-rain-sound' THEN '雨音を録る音響技師と、消えたあなたの足音を探す'
  ELSE title
END,
pack_json = json_set(
  pack_json,
  '$.title',
  CASE id
    WHEN 'aoi' THEN '明日この町を出る幼なじみと、最後の夜の秘密'
    WHEN 'mia' THEN '馴染みのエルフ店主と、閉店後の酒場で和平条約を守る夜'
    WHEN 'rin' THEN '閉館後の図書館で、司書の彼女と「明日を記す日記」を読む'
    WHEN 'koharu' THEN '画家の女友達に、明日の日付の「あなたの肖像」を見せられる'
    WHEN 'minato-radio' THEN '三年間声だけ知るラジオDJと、最終回後に初めて会う'
    WHEN 'satoru-ren' THEN '嵐の観測所で、寡黙な技師と年下ガイドに決断を託される'
    WHEN 'yu' THEN '毎週花束を買う年下の常連と、八回目の金曜日の秘密'
    WHEN 'ritsu' THEN '祖母の家を空にする日、年上の遺品整理士と秘密の手紙を探す'
    WHEN 'shizuku-downer' THEN '男嫌いのダウナーな後輩が、放課後はあなたにだけ甘える'
    WHEN 'lucien-contract' THEN '「愛さない」契約を結んだ公爵が、あなたにだけ嘘をつけない'
    WHEN 'kohaku-midnight' THEN '午前二時、狐の常連から「会えなくなる恩返し」を差し出される'
    WHEN 'tomoya-fake-date' THEN '無口な同期と、元恋人の結婚式で一日だけ恋人になる'
    WHEN 'noah-voice-memory' THEN '記憶を失った相棒が、あなたの声だけを覚えている'
    WHEN 'cassian-rewind' THEN '処刑前夜、裏切った護衛をもう一度だけ共犯にする'
    WHEN 'sumiko-rules' THEN '家賃千円の訳あり部屋で、年上の管理人と最後の規則を探す'
    WHEN 'vera-diner' THEN '元魔王の美人店員と、閉店後の定食屋で皿洗い'
    WHEN 'elias-dragons' THEN '追放されたあなたを、無愛想な竜の保育士が迎えに来る'
    WHEN 'shinkuro-road' THEN '雨の宿場で、名を捨てた浪人と一夜限りの護衛旅'
    WHEN 'lionel-shutdown' THEN 'サービス終了の夜、ずっと旅した相棒NPCに別れを頼まれる'
    WHEN 'marta-socks' THEN '世話焼きな魔女と、明日のあなたから届いた片方の靴下を追う'
    WHEN 'seiji-memory' THEN '記憶を売った刑事と、消えた「昨日」を二人で買い戻す'
    WHEN 'maho-last-bout' THEN '引退試合の前夜、元ライバルの彼女がセコンドに来る'
    WHEN 'genmei-poison' THEN '後宮の毒見役が、あなたの薬膳だけを疑う夜'
    WHEN 'natsu-final-live' THEN '解散ライブ五分前、相方が二人だけの新曲を持ってくる'
    WHEN 'rei-blue-bird' THEN '閉館後の美術館で、怪盗の彼女から「盗まない共犯」を頼まれる'
    WHEN 'naoto-two-weeks' THEN '離婚届を出した元夫と、最後の二週間だけ同居する'
    WHEN 'ryo-alliance' THEN '昨日まで敵だった弁護士と、証人を守る秘密の同盟を結ぶ'
    WHEN 'mina-offline' THEN '人気配信者の彼女が、配信を切ってあなたにだけ本名を明かす'
    WHEN 'nagi-radio' THEN '沈んだ観測所から、十年前に失った相棒の声が届く'
    WHEN 'shuji-last-train' THEN '廃駅の駅員と、終電名簿にあるあなたの名前を消す夜'
    WHEN 'fumie-family-tree' THEN '無口な刺繍師と、家系図から消えたあなたの名前を縫い戻す'
    WHEN 'saku-unscripted' THEN '恋愛番組を降りた俳優と、カメラのない夜道を二人で歩く'
    WHEN 'akari-foldroad' THEN '勝ち気な配達員と、地図にない町へ最後の荷物を届ける'
    WHEN 'gald-career' THEN '世界を救った元勇者と、二人きりで初めての履歴書を書く'
    WHEN 'yayoi-extra-day' THEN '新人死神の数え間違いで、あなたと彼女に一日だけ猶予ができる'
    WHEN 'sena-mars-flower' THEN '火星植物園の研究員と、あなたにだけ咲く地球最後の花を守る'
    WHEN 'lucas-nightmare' THEN '夢の競売人と、売ったはずのあなたの悪夢を買い戻す'
    WHEN 'julius-handover' THEN '退職する魔法使いと、家族同然の使い魔へ最後の引継ぎを書く'
    WHEN 'someta-new-story' THEN '声を失った落語家と、深夜の楽屋で二人だけの新作を作る'
    WHEN 'saya-forecast' THEN '気象予報士の彼女と、あなたの名前を呼ぶ明日の予報を確かめる'
    WHEN 'margot-awake' THEN '百年眠る城で、毒舌な清掃員と王子より先に目覚める'
    WHEN 'kiryu-future-letter' THEN '未来郵便局の配達員と、十年後のあなたの「読むな」を預かる'
    WHEN 'ritsuko-full-house' THEN '幽霊専門の年上鑑定士と、六人が暮らす空き家で一夜を過ごす'
    WHEN 'ian-final-word' THEN '世界最後の翻訳者と、AIが遺した別れの一語を選ぶ'
    WHEN 'hiyori-moon-store' THEN '月面コンビニの夜勤店員と、七分遅れの最後の客を待つ'
    WHEN 'sota-dragon-bath' THEN '竜専門の番頭と、湯船を怖がる最後の一匹を見守る'
    WHEN 'chifuyu-last-match' THEN '引退を決めた棋士と、盤上から消えた封じ手を追う'
    WHEN 'genta-cold-well' THEN '火消し頭と、燃えていない家の井戸から昇る白煙を追う'
    WHEN 'agnes-unordered-dish' THEN '王宮の給仕長と、誰も頼んでいない最後の銀皿を開ける'
    WHEN 'haruto-jellyfish' THEN '閉館後の水族館で、夜勤飼育員と眠らないクラゲを見守る'
    WHEN 'kei-imperfect-dish' THEN '無口なシェフが、収録後の厨房であなたにだけ失敗作を出す'
    WHEN 'takumi-repaired-chair' THEN '別れた家具職人と、二人で選んだ椅子の行き先を決める'
    WHEN 'hibiki-rain-sound' THEN '雨音を録る音響技師と、消えたあなたの足音を探す'
    ELSE json_extract(pack_json, '$.title')
  END
),
updated_at = unixepoch()
WHERE id IN (
  'aoi', 'mia', 'rin', 'koharu', 'minato-radio', 'satoru-ren', 'yu', 'ritsu',
  'shizuku-downer', 'lucien-contract', 'kohaku-midnight', 'tomoya-fake-date',
  'noah-voice-memory', 'cassian-rewind', 'sumiko-rules', 'vera-diner', 'elias-dragons',
  'shinkuro-road', 'lionel-shutdown', 'marta-socks', 'seiji-memory', 'maho-last-bout',
  'genmei-poison', 'natsu-final-live', 'rei-blue-bird', 'naoto-two-weeks', 'ryo-alliance',
  'mina-offline', 'nagi-radio', 'shuji-last-train', 'fumie-family-tree', 'saku-unscripted',
  'akari-foldroad', 'gald-career', 'yayoi-extra-day', 'sena-mars-flower', 'lucas-nightmare',
  'julius-handover', 'someta-new-story', 'saya-forecast', 'margot-awake',
  'kiryu-future-letter', 'ritsuko-full-house', 'ian-final-word', 'hiyori-moon-store',
  'sota-dragon-bath', 'chifuyu-last-match', 'genta-cold-well', 'agnes-unordered-dish',
  'haruto-jellyfish', 'kei-imperfect-dish', 'takumi-repaired-chair', 'hibiki-rain-sound'
);
