-- Generated by integrate_mikan_idle_videos.mjs. Static images remain as fallbacks.

UPDATE scenarios
SET pack_json = json_set(pack_json, '$.version', '1.0.2', '$.plot.characters[0].extensions."mikan.motion"', json('{"idleVideoUrl":"/scenario-motion/downer-girl-first-love-shizuku-idle.mp4"}')), updated_at = unixepoch()
WHERE json_extract(pack_json, '$.id') = 'f0b4e40f-6596-4e14-bef5-fa5707faabac';

