-- 配信済みパックの voice.profile に gender を付与する。
-- examples/*/pack.json が正本。locals で付与済みの gender を D1 へ反映する。
-- resolveScenarioVoice の profileGender フォールバックで既存の声選択も自己修復する。

UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '0e8c9650-f27c-41a4-9187-c57d774624d2' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '80255efe-1ad8-4383-9d07-162bec8e8cfb' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'cc1374b1-3147-4790-9e51-a0a3b4d01019' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '349390e1-a02a-4ec3-ab89-ab8bd37762af' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '492027a4-1114-4f61-8035-b2790b797a14' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '9dddf1cf-afa0-4e23-be99-3b34f6ba0c94' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'f0b4e40f-6596-4e14-bef5-fa5707faabac' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '5825c374-c85d-4698-af9d-997cde5c709a' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'fb6c1871-75cc-4693-8a3c-c0e0f52d848d' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'b64e924e-d4e4-4a8f-8518-75c7bf6341d8' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '539724bc-012e-4c2c-9859-cafe088de4c9' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '5231b131-5fb3-43a6-adb3-34d5e5964f16' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '80f09728-d51f-420a-b8fd-69281e8d3369' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '3d16867d-139f-4f57-928b-e01174f81247' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'ac8c9844-07a5-4d43-952d-947acd152129' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'bfecfbc5-3151-471a-8d6b-830807680e4f' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '22d39c60-1eb6-4408-a9f1-b1b352fd4389' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'a5cba745-89f5-4954-9713-64789657f23e' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'dfcd18ad-98b3-42f6-b1dd-b73a985fcd36' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'b8c82d49-c712-4fa3-922a-598910ccb6d5' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '44209dad-7f50-4c6b-a1dd-f03b7b91b971' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'd1b11805-c415-45d8-beaa-13cd17368c15' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'e3c53f1d-c7c4-425d-85bc-594aff965c4e' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '55d8c2cf-02de-4867-9883-9082924e9dc4' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '256656a8-15f8-4ebf-b699-08614e6ad2ec' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '0dfbf679-2ce1-4106-a659-4d38ac038a27' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '1ca39e23-0040-4afb-ae13-3dbe061f5d9c' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'ad7e145d-a985-45aa-a8ec-de3894e33773' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'f0e1e05b-0d6a-4c9b-8913-5c7b6fa5a475' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'f9bb1e5c-c006-4a48-a3d0-6da8eb2fa143' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '68940f74-fdb8-4c0e-8508-d6e4465fc2a2' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '8a54ff56-7a59-492d-9e1d-f47b4403086e' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'aefa2304-3be2-4f40-a28c-373f2d1ee823' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'f8d2901e-6cf0-484c-9314-2d01041662d9' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '289457f4-e758-4c30-86f3-3a59a461473f' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'd2b86c7c-f81b-4f61-b576-7a1793014679' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '5e17395e-79b0-4b46-8e55-4ddac9a8e787' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'f2a0fafc-1113-464d-9247-8acd69acca2b' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '5d23cde0-1c2d-4fa6-a75f-3767cdbab327' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '3a77822b-078a-48ce-8788-93969ffc82a6' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '3d223e98-ee1c-4ea4-bf5a-a1e0757b1427' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'e3d901ae-fdda-451e-8e0f-5723200eb586' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '7ce81838-1a82-44fe-b41a-5a1fbebeb94f' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '348a27cc-9a61-4592-a056-666c3b2e3529' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'a612cd4f-c085-41cb-8b5e-929f5b43136c' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[1].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'a612cd4f-c085-41cb-8b5e-929f5b43136c' AND json_extract(pack_json, '$.plot.characters[1].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[1].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'd4f30872-89c7-4e4d-93ad-c2343b857c1d' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'decb4a4e-9e57-46cf-8f27-8ded090f4e24' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'ec90f80d-1a6e-4b33-961a-1f9c94cd991c' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = 'cece21de-f0af-45f2-b1a0-ab4bea7df0e4' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '5d437745-e0e5-4cb7-a2f9-656c75540f79' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE json_extract(pack_json, '$.id') = '937ba756-e97a-42b2-ae8a-181424064eb0' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;

-- バンドル4キャラと元カレは examples に対応物がないため直接指定する。
-- mia（快活なエルフの酒場店主）: female、noah（寡黙な護衛）: male。
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE id = 'mia' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[1].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE id = 'mia' AND json_extract(pack_json, '$.plot.characters[1].id') = 'noah' AND json_extract(pack_json, '$.plot.characters[1].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[1].voice.profile.gender') IS NULL;
-- rin（図書館司書の先輩）: female。
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'female'), updated_at = unixepoch() WHERE id = 'rin' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
-- kaito（元カレのタクマ）: male。
UPDATE scenarios SET pack_json = json_set(pack_json, '$.plot.characters[0].voice.profile.gender', 'male'), updated_at = unixepoch() WHERE id = 'kaito-ex-wedding' AND json_extract(pack_json, '$.plot.characters[0].voice.profile') IS NOT NULL AND json_extract(pack_json, '$.plot.characters[0].voice.profile.gender') IS NULL;
